Yf backend rewrite
Wintergatan/Tightinator pull request #48
Opened 2023-08-29 11:07 UTC by YanFett

It happened!
a complete overhaul of the Backend.
Featuring:

- Very fast computation due to extensive usage of numpy instead of for loops!
- A Overhaul of most commandline arguments!
- No more Downsampling! Who needs that when you got numpy!
- Two different peakfinders: Center of weight or center of weight followed by correlation!
- Peakfinding by correlation: A "just shove them damn roguepeaks where they fit in" approach!
- A Clean Workflow with (limited) documentation for the important bits!
- The same old and beloved plots with minor improvements!
- CSV export of the same data thats actually plotted!

2023-08-30 11:25 UTC, TLMcNulty requested changes
Left comments. Basically nothing of any substance on the actual logic, just layout and conventions.

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +    return np.abs(array / np.max(np.abs(array)))
Comments out of order, see comment on roughpeaks(), but again I question the needed for an entire function "def normalize()" when its contents are a one line return doing a math operation. Code complexity and lines overall can be reduced by refactoring this function into one math operation on line 231.

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +    return 1 / (np.sqrt(2 * np.pi) * sigma) * np.exp(-0.5 * ((x - mu) / sigma)**2)
See similar comments about function complexity. I can understand wanting to place obscure math operations behind clean function names, but a comment block immediately proceeding this math operation may be simpler than having to scroll down to the function to view its contents when debugging or refactoring in the future.

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +def peakrefiner_center_of_weight(signal, oldpeakSamples, chunksize):
Good example of pythonic function name, lowercase with underscores. Aim to make variable/function names consistent. 

Furthermore, this is an example of an appropriate use of a function. Multiple serial operations are being done to the functions inputs here and the logic operation is progressing. 

However, the number one reason we define functions is to allow for their versatility and reuse. It may, in the long run, be easier to read this script's functions if the logic in this section was instead above and in an appropriate place procedurally during peak refining, with a section comment explaining the next few lines will create a new peak array by shifting the weight peak by peak.

To expand on the above re: versatility, functions allow you to reduce the number of times you're forced to repeat yourself; D.R.Y - "Don't repeat yourself."

If peaks were passed one at a time to this function, having it would reduce repetition. Instead, as far as I can tell, all the peaks are passed at once in an array, thus forcing the reader to leave the procedural portion of the script to check the contents of a function that is called once, and then return to where it was called to continue reading the script logic. Functions that are called once are not reducing repetition.

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +    power =1.5
Nit: space after the equals sign

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +def drawline(fig,legendstr,posSample,chunkheight,vertical=True,color="black",dash="dashed"):
See comments re: function/variable names

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +def plotchunksim(chunks,time,chunksize, full_width, plot_height):
See comments re: function/variable names.

Inconsistent comma/spacing in arguments.

2023-08-30 11:25 UTC, TLMcNulty commented on main.py
> +def plot_centered(fig, signal, time,peakSamples, bestpeakSamples,chunksize,meanDiff,stdDiff,bestmeanDiff,beststdDiff):
Inconsistent commas/spacing in arguments.

Additionally we depart from the function documentation we had in earlier examples.

2023-08-30 17:32 UTC, YanFett commented
Adressed al requested changes except for the rough_peaks function which now is slightly longer than one line.

2023-08-31 19:03 UTC, TLMcNulty approved these changes

2023-08-31 19:03 UTC, merged